version: "3.8"

services:

  db:
    image: postgres:15
    container_name: ecommerce_database
    restart: always

    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"



  backend:
    build:
      context: ./backend

    container_name: ecommerce_backend

    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - db



  frontend:
    build:
      context: ./frontend

    container_name: ecommerce_frontend

    ports:
      - "3000:80"

    depends_on:
      - backend



volumes:

  postgres_data:












































# version: "3.8"

# services:

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: ecommerce_backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     environment:
#       - PYTHONUNBUFFERED=1
#     command: python manage.py runserver 0.0.0.0:8000


#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: ecommerce_frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     depends_on:
#       - backend
#     command: npm start