"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 3.2.4.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables
load_dotenv()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-*7!!kc@bmtx8ngui6lr@xmifmcwm6y%hnbe)rdei(b!ds8t)uq"
)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "backend",
    "0.0.0.0",
]


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'corsheaders',

    # Local apps
    'product',
    'payments',
    'account',
]


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    # CORS
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'my_project.urls'


TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


WSGI_APPLICATION = 'my_project.wsgi.application'



# =====================================================
# DATABASE - POSTGRESQL
# =====================================================

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv("DB_NAME"),

        "USER": os.getenv("DB_USER"),

        "PASSWORD": os.getenv("DB_PASSWORD"),

        "HOST": os.getenv("DB_HOST"),

        "PORT": os.getenv("DB_PORT"),

    }

}



# =====================================================
# Password validation
# =====================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME': 
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME': 
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]



# =====================================================
# Internationalization
# =====================================================

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True


USE_L10N = True


USE_TZ = True



# =====================================================
# JWT Configuration
# =====================================================

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    'ROTATE_REFRESH_TOKENS': False,

    'BLACKLIST_AFTER_ROTATION': True,

    'UPDATE_LAST_LOGIN': False,


    'ALGORITHM': 'HS256',

    'VERIFYING_KEY': None,

    'AUDIENCE': None,

    'ISSUER': None,


    'AUTH_HEADER_TYPES': ('Bearer',),

    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',


    'USER_ID_FIELD': 'id',

    'USER_ID_CLAIM': 'user_id',


    'AUTH_TOKEN_CLASSES': (
        'rest_framework_simplejwt.tokens.AccessToken',
    ),

    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

}



REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',

    )

}



# =====================================================
# Stripe
# =====================================================

STRIPE_TEST_PUBLISHABLE_KEY = os.getenv(
    "STRIPE_TEST_PUBLISHABLE_KEY"
)


STRIPE_TEST_SECRET_KEY = os.getenv(
    "STRIPE_TEST_SECRET_KEY"
)



# =====================================================
# Static & Media
# =====================================================

STATIC_URL = '/static/'


MEDIA_URL = '/images/'


STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static'),

]


MEDIA_ROOT = os.path.join(
    BASE_DIR,
    "static/images"
)



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# =====================================================
# CORS
# =====================================================

CORS_ALLOW_ALL_ORIGINS = True