name: Full Stack Ecommerce CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  backend-test:

    name: Backend Django Test

    runs-on: ubuntu-latest


    services:

      postgres:
        image: postgres:15

        env:
          POSTGRES_DB: ecommerce_db
          POSTGRES_USER: ecommerce_user
          POSTGRES_PASSWORD: ecommerce_password

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"


      - name: Install backend dependencies
        working-directory: backend
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Django migrations
        working-directory: backend
        env:
          DB_NAME: ecommerce_db
          DB_USER: ecommerce_user
          DB_PASSWORD: ecommerce_password
          DB_HOST: localhost
          DB_PORT: 5432

        run: |
          python manage.py migrate


      - name: Run Django tests
        working-directory: backend
        env:
          DB_NAME: ecommerce_db
          DB_USER: ecommerce_user
          DB_PASSWORD: ecommerce_password
          DB_HOST: localhost
          DB_PORT: 5432

        run: |
          python manage.py test



  frontend-test:

    name: React Build Test

    runs-on: ubuntu-latest


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"


      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm ci


      - name: Fix react-scripts permission
        working-directory: frontend
        run: |
          chmod +x node_modules/.bin/react-scripts


      - name: Build React application
        working-directory: frontend
        run: |
          npm run build



  docker-build:

    name: Docker Image Build

    runs-on: ubuntu-latest


    needs:
      - backend-test
      - frontend-test


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build backend image
        run: |
          docker build -t ecommerce-backend ./backend


      - name: Build frontend image
        run: |
          docker build -t ecommerce-frontend ./frontend
